<?php /* @var $this Mmartinovic_Coeditor_Block_Adminhtml_Sales_Order_View_Coeditor_Options */ ?>
<?php $options = Mage::helper('core')->decorateArray($this->getOptions()); ?>
<?php if (count($options)): ?>
<?php echo $this->getChildHtml('options_js') ?>

<div id="coeditor_fields_options" class="<?php echo $this->getIsLastFieldset() ? 'last-fieldset' : '' ?>">
    <h4><?php echo Mage::helper('catalog')->__('Custom Options') ?></h4>
    <div class="product-options">
        <dl>
            <?php foreach($options as $option): ?>
                <?php echo $this->getOptionHtml($option); ?>
            <?php endforeach;?>
        </dl>
    </div>
</div>
<?php endif; ?>